# Generated by Django 2.2.2 on 2019-06-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('youtube_url', models.CharField(blank=True, default='', max_length=300)),
                ('song_tab', models.CharField(blank=True, default='', max_length=100)),
                ('lyrics', models.CharField(blank=True, default='', max_length=2000)),
                ('skill_level', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('black_belt', 'Black Belt')], default='intermediate', max_length=200)),
            ],
        ),
    ]
