# Generated by Django 2.2.2 on 2019-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_url',
            new_name='youtube_tutorial',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
