# Generated by Django 2.2.2 on 2019-06-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0002_auto_20190625_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='skill_level',
            new_name='experience_level',
        ),
    ]
