# Generated by Django 2.2.2 on 2019-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0003_auto_20190625_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='experience_level',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Black_Belt', 'Black Belt')], default='intermediate', max_length=200),
        ),
    ]
